### ISSUE TITLE
Nuisance warning

### ISSUE THREAD

**Issue by Coding-Badly** [stanislav-tkach/os_info#236]
For about half the Amazon Web Service (AWS) images `lsb_release` is not installed.

`os_info` first tries to use `lsb_release` to get version information.  If that fails various files are checked.

So, for about half the AWS images `os_info` ends up performing file checks.  That path is essentially a normal path.

The end result is that [this warning](https://github.com/stanislav-tkach/os_info/blob/master/os_info/src/linux/lsb_release.rs#L58) is a nuisance.  For about half the AWS images that warning is always output despite the fact that `os_info` goes on to correctly identify the version.

The suggestion is to either eliminate the `warn!` or change it to `debug!`.

**Comment by stanislav-tkach** [comment]
Closed with #237.
