### ISSUE TITLE
Alpine 3.13 incompatible

### ISSUE THREAD

**Issue by marvinpan8** [stanislav-tkach/os_info#247]
Error log:
2021-02-04 14:28:30 WARN [os_info::imp::lsb_release] lsb_release command failed with Os { code: 2, kind: NotFound, message: "No such file or directory" }

rust version: 
rustc 1.44.1 (c7087fe00 2020-06-17)
```
$ cat /etc/issue 
Welcome to Alpine Linux 3.13
Kernel \r on an \m (\l)

$ ls /etc/*release
/etc/alpine-release  /etc/os-release

$ cat /etc/alpine-release
3.13.0

$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by Coding-Badly** [comment]
It looks like the [current level for that message](https://github.com/stanislav-tkach/os_info/blob/6471d530a0c3760c417543015135d5c87a2f6da4/os_info/src/linux/lsb_release.rs#L58) is `DEBUG`.  Which version of this crate are you using?

**Comment by stanislav-tkach** [comment]
Sorry for the late reply and thanks for your report! Could you please elaborate if you are getting any other meaningful output from the library? Did you get some version information?

In case you are only concerned with the error in logs, @Coding-Badly is right: this message should have the `debug` level in the latest version.

**Comment by stanislav-tkach** [comment]
Feel free to reopen if you have more questions.
