### ISSUE TITLE
Illumos/Solaris support

### ISSUE THREAD

**Issue by martintc** [stanislav-tkach/os_info#297]
Feature request: Add in support for Illumos and Solaris based systems.

This is mostly a reminder for me to take a look into this once I get the BSD's supported. Feel free to place me as the assignee.

Also, for anyone to mention if they need support for a specific illumos/solaris system to place it here, then I can tackle the ones most requested first.

**Comment by martintc** [comment]
Initial implementation in review in PR #305

**Comment by stanislav-tkach** [comment]
@martintc Thanks again for the pull request. Do you think something else needs to be done to close this issue?

**Comment by martintc** [comment]
> @martintc Thanks again for the pull request. Do you think something else needs to be done to close this issue?

No problem at all. I think with landing initial support for Solaris/Illumos systems, should be good enough to close the issue. If we want to support any more distributions, it should be just a variation of the merged in branch. So on my end, I am fine with closing it.

**Comment by stanislav-tkach** [comment]
@martintc Thanks for the quick response!
