### ISSUE TITLE
Breakage with FreeSBD

### ISSUE THREAD

**Issue by martintc** [stanislav-tkach/os_info#308]
os_info on vanilla FreeBSD now reports back as unknown. I was notified by @kraileth via email. Will work on getting a fix for this going. Looked at the PR (#303) and double checked that @kraileth tested it and it worked then. I also remember not having any issues during my testing. The only explanation I can think of is that there has been a change to FreeBSD that broke the expected behavior I wrote against.

**Comment by martintc** [comment]
Can we get like a 3.2.1 patch release?

**Comment by stanislav-tkach** [comment]
@martintc I have just released the 3.4.0 version. It isn't 3.3.1 because it contains Gentoo detection.
