### ISSUE TITLE
Bug: OracleLinux false detections

### ISSUE THREAD

**Issue by exincore** [stanislav-tkach/os_info#315]
I believe I have found how this module has been falsely identifying so many operating systems as OracleLinux. See:
- #301 
- #275 
- [starship/starship#3936](https://github.com/starship/starship/issues/3936)

## Failure Mode
1. `linux/mod.rs` is run
2. `lsb_release` is not installed and fails properly; `linux/mod.rs` falls back to `file_release`
3. Using an array of 6 predefined `DISTRIBUTIONS`, `file_release` will initially attempt to read a `{mariner,centos,fedora,alpine}-release`, each of which fail properly to the next in the array since those files do not exist in this scenario.
4. `file_release` arrives at `os-release` with a fallback Type as `OracleLinux` as defined in `DISTRIBUTIONS`. The `os-release` file DOES exist and a parsing attempt is made.
5. The parser `Matcher::KeyValue` searches for "NAME"
6. **The `get_type` function attempts to convert the identified name string into a `Type`, but fails to match due to not being robust enough: lacking any sort of fuzzy matching or regex, the NAME field not existing, or having a limited list of potential matches.**
7. **With `None` returned by `get_type`, `file_release` uses the fallback Type `OracleLinux`** from the current array element, and proceeds to identify the version as it would any other `os-release`.
8. With a `Type` and `Version` in hand, `file_release` returns, short-circuiting any other array elements defined in `DISTRIBUTIONS` as long as `os-release` exists.
9. The wrong `Type` of `OracleLinux` is returned, while `Version` is correct as it is specific to `os-release` and not the returned `OracleLinux`.

## Notes
- Tests do not cover iteration of the `DISTRIBUTIONS` array but instead skip to using the known correct element, therefore the tests for the 6th element `RedHatEnterprise` cannot uncover the short-circuit caused by the 5th element, `OracleLinux`.
- From what I can tell, inside of `os-release`, the `ID` field is much more stable than `NAME` and is designed to be more script-friendly.
- This structure prevents a `Type` of `Linux` from ever being returned as long as `os-release` exists. That is, many Linux distributions that this module cannot identify specifically, and *should* fallback to just `Linux`, will instead be identified as `OracleLinux` as long as `os-release` exists on the distribution.
  - Note that for #301, Gentoo cannot be identified by `file_release`, so if `lsb_release` is not installed, Gentoo will always be identified as `OracleLinux`. Though, Gentoo has its own specific `gentoo-release` file that should be checked by this crate anyway.

**Comment by davidkna** [comment]
Instead of fuzzy matching, looking at `ID` (and `ID_LIKE`) likely works better than `NAME` for parsing, and is less likely to require any fuzzy matching.

**Comment by exincore** [comment]
I'll go ahead and fork and see if I can take a swing at improving `get_type` slightly.

**Comment by exincore** [comment]
I found a resource for the os-release files to cross reference with what `ID` fields I know: https://github.com/chef/os_release

**Comment by stanislav-tkach** [comment]
Thank you for the very detailed bug report! And sorry for the late reply - I have recently changed a job, so not it takes most of my free time. I see you drafted the pull request and will try to look into it.
