### ISSUE TITLE
Add information about processor architecture

### ISSUE THREAD

**Issue by rbas** [stanislav-tkach/os_info#335]
Processor architecture is also useful information. Would be nice to have it as part of `Info`.

_Actually, I have already use-case. This crate is used by [Starship](https://starship.rs) and I would display architecture in my command line promt. I'm using arm architecture from Apple and switching terminals in between that and emulated `x86_64`._

**Comment by stanislav-tkach** [comment]
Closed by https://github.com/stanislav-tkach/os_info/pull/336.

**Comment by stanislav-tkach** [comment]
What do you think about making the architecture enum instead of string?
