### ISSUE TITLE
Consider bumping windows-sys dependency

### ISSUE THREAD

**Issue by ydirson** [stanislav-tkach/os_info#356]
By updating to `os_info` master, my project is pulling a 3rd version of windows dependencies: 0.45 is now old with 0.52 being out, and many crates still pulling 0.48.
It would be great to have a version specification wider than just `^0.45.0`, maybe `>= 0.45.0` would be accurate enough?
It would require proactive checking for new incompatible version, though, but that could be done using a CI job notifying as soon as an incompatible change lands on their own master.

**Comment by stanislav-tkach** [comment]
Should be done as part of https://github.com/stanislav-tkach/os_info/pull/366.
