### ISSUE TITLE
CI tests not run

### ISSUE THREAD

**Issue by ydirson** [stanislav-tkach/os_info#362]
The `tests` job in `CI` workflow just does not run.  Tried [this](https://github.com/xcp-ng/rust-os_info/commit/2c09fa50519160ecbad8dd72aeee730c20f4df43), but it is apparently not even sufficient.  Baffled that Github does not even give any warning about that situation.

Quite annoying, `master` build has been broken by the incomplete Ultramarine PR :frowning_face:

**Comment by stanislav-tkach** [comment]
I'm aware of the issue, but thanks for reminding me about it. I will really try to fix everything next week.

**Comment by stanislav-tkach** [comment]
Should be fixed by https://github.com/stanislav-tkach/os_info/pull/366.
