### ISSUE TITLE
3.8.0 broken on illumos

### ISSUE THREAD

**Issue by citrus-it** [stanislav-tkach/os_info#371]
As of version 3.8.0, this crate fails to compile on illumos:

```
error[E0308]: mismatched types
  --> /home/af/.cargo/registry/src/index.crates.io-6f17d22bba15001f/os_info-3.8.0/src/illumos/mod.rs:32:14
   |
31 |     match uname("-o") {
   |           ----------- this expression has type `std::option::Option<std::string::String>`
32 |         Some("illumos") => Type::Illumos,
   |              ^^^^^^^^^ expected `String`, found `&str`
```

**Comment by sunshowers** [comment]
Can os_info use nix or libc's uname support? https://docs.rs/nix/0.28.0/nix/sys/utsname/fn.uname.html

**Comment by stanislav-tkach** [comment]
@sunshowers I think it is a good idea, but I prefer to experiment with it later and quickly fix current issues with a simple patch. I have created an issue (https://github.com/stanislav-tkach/os_info/issues/375) to return to this later.
