### ISSUE TITLE
Released versions contain test data

### ISSUE THREAD

**Issue by weiznich** [stanislav-tkach/os_info#389]
While reviewing some updates to our dependencies I noticed that the last version (3.9.0) of `os_info` uploaded to crates.io contains unnecessary test data in `src/linux/tests`. While this is not a problem on it's own it is at least wasteful as these data need not to be there for having a correctly working crate.

Cargo allows to exclude such files via an entry in your `Cargo.toml` file: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields

See the diff here: https://diff.rs/os_info/3.8.2/3.9.0/

If you are interested in addressing that I'm happy to contribute a PR for this.

**Comment by stanislav-tkach** [comment]
This seems reasonable, thanks for the suggestion! If you want to do that - go ahead, I would be happy if this is addressed.
